version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    schedule:
      interval: monthly
  - package-ecosystem: nuget
    directories:
      - /
      - /src/RustDeskHop
      - /tests/RustDeskHop.Tests
      - /tools/BrandingRenderer
    target-branch: develop
    schedule:
      interval: monthly
